export default {
  CHANGE_DIRECTORY: 'CHANGE_DIRECTORY',

  LIST_DIRECTORY: 'LIST_DIRECTORY',

  PARENT_DIRECTORY: 'PARENT_DIRECTORY',

  PERSIST_REHYDRATE: 'persist/REHYDRATE',

  SET_FILE: 'SET_FILE',

  SET_FILES: 'SET_FILES',

  SET_VIDEO_PREFS: 'SET_VIDEO_PREFS',

  SET_WINDOW_SIZE: 'SET_WINDOW_SIZE',
  SET_WINDOW_SIZE_SUCCESS: 'SET_WINDOW_SIZE_SUCCESS',
};
