export default {
  CHANGE_DIRECTORY: 'CHANGE_DIRECTORY',
  PARENT_DIRECTORY: 'PARENT_DIRECTORY',

  PERSIST_REHYDRATE: 'persist/REHYDRATE',

  FIRST_MEDIA_FILE: 'FIRST_MEDIA_FILE',
  
  NEXT_FILE: 'NEXT_FILE',
  RANDOM_FILE: 'RANDOM_FILE',
  SET_FILE: 'SET_FILE',

  SET_FILES: 'SET_FILES',

  SET_IMAGE_PREFS: 'SET_IMAGE_PREFS',

  SET_VIDEO_PREFS: 'SET_VIDEO_PREFS',

  SET_WINDOW_SIZE: 'SET_WINDOW_SIZE',
  SET_WINDOW_SIZE_SUCCESS: 'SET_WINDOW_SIZE_SUCCESS',
};
